require conf/machine/include/qcom-common.inc
require conf/machine/include/arm/arch-armv8a.inc

MACHINE_FEATURES = "usbhost usbgadget alsa screen wifi bluetooth ext2"

# UFS partitions in 820/845/RB5 setup with 4096 logical sector size
EXTRA_IMAGECMD:ext4 += " -b 4096 "

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"

# Support for dragonboard{410, 820, 845}c, rb5
KERNEL_IMAGETYPE ?= "Image.gz"
SERIAL_CONSOLE ?= "115200 ttyMSM0"
KERNEL_DEVICETREE ?= " \
    qcom/qrb5165-rb5.dtb \
"

# These DT are not upstreamed (yet) and currenty exist only as a patches against linux-yocto
KERNEL_DEVICETREE:append:pn-linux-yocto = " \
    qcom/qcm6490-idp.dtb \
    qcom/qcs6490-rb3gen2.dtb \
"

QCOM_BOOTIMG_ROOTFS ?= "/dev/sda8"
# Userspace tools
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    pd-mapper \
    qrtr \
    rmtfs \
    tqftpserv \
"

MACHINE_EXTRA_RRECOMMENDS += " \
    fastrpc \
"

# Modules and firmware for all supported machines
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    kernel-modules \
    ${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'mesa-driver-msm', '', d)} \
    ${@bb.utils.contains('DISTRO_FEATURES', 'wifi', 'wireless-regdb-static', '', d)} \
    packagegroup-firmware-rb5 \
"

MACHINEOVERRIDES =. "qcom-armv8a:"

IMAGE_FSTYPES ?= "ext4"
